// Constantes “domaine” partagées (carte + place)
export const BUILDINGS = [
  {
    id: 'chateau',
    label: 'Château (Projets)',
    x: 25,
    y: 39,
    href: '#/chateau',
    icon: 'castle',
    emoji: '🏰',
    desc: 'Mes projets personnels…',
  },
  {
    id: 'caserne',
    label: 'Caserne (Formations)',
    x: 60,
    y: 62,
    href: '#/caserne',
    icon: 'barracks',
    emoji: '⚔️',
    desc: 'Formations, compétences…',
  },
  {
    id: 'auberge',
    label: 'Auberge (Passe-temps)',
    x: 56,
    y: 29,
    href: '#/auberge',
    icon: 'tavern',
    emoji: '🍻',
    desc: 'Jeux vidéo & société…',
  },
  {
    id: 'place',
    label: 'Place du village',
    x: 46,
    y: 35,
    href: '#/place',
    icon: 'plaza',
    emoji: '🧭',
    desc: 'Index accessible.',
  },
  {
    id: 'cv',
    label: 'Salle des archives',
    x: 38,
    y: 23,
    href: '#/cv',
    icon: 'archives',
    emoji: '📜',
    desc: 'CV imprimable.',
  },
  {
    id: 'forge',
    label: 'Forge (Hard Work)',
    x: 38,
    y: 46,
    href: '#/forge',
    icon: 'forge',
    emoji: '⚒️',
    desc: 'Travail en cours',
  },
  {
    id: 'grotte',
    label: 'Knowhere',
    x: 14,
    y: 86,
    href: '#/grotte',
    icon: null,
    emoji: '🌀',
    desc: 'Knowhere',
    hidden: true
  },
  // { id: 'biblio', label: 'Bibliothèque', x: 58, y: 60, href: '#/biblio', icon: 'book', emoji: '📚', desc: 'Lectures, notes.' },
]
